name = snowflake-sink-connector
connector.class = com.snowflake.kafka.connector.SnowflakeSinkConnector
tasks.max = 1
topics = customer_topic
snowflake.url.name = https://<host>.snowflakecomputing.com:443
snowflake.user.name = KAFKA_USER
snowflake.private.key = <privatekey>
snowflake.database.name = KAFKA_TEST
snowflake.schema.name =  INGESTION
snowflake.table.name = CUSTOMER
snowflake.role.name = KAFKA_CONNECTOR_ROLE
